server:
  port: 10005
spring:
  # Application 的配置项
  application:
    name: sentinel-demo
  # Profile 的配置项
  profiles:
    active: dev
  cloud:
    nacos:
      # Spring Cloud Nacos Discovery 配置项
      discovery:
        server-addr: 127.0.0.1:8848 # Nacos 服务器地址
      #        namespace: dev # Nacos 命名空间
      config:
        server-addr: 127.0.0.1:8848 # Nacos 服务器地址
        namespace: fd1c783d-1d40-45ee-ac6a-c2e4778d50eb # 使用的 Nacos 的命名空间，默认为 null
        group: DEFAULT_GROUP # 使用的 Nacos 配置分组，默认为 DEFAULT_GROUP
        name: # 使用的 Nacos 配置集的 dataId，默认为 spring.application.name
        file-extension: yaml # 使用的 Nacos 配置集的 dataId 的文件拓展名，同时也是 Nacos 配置集的配置格式，默认为 properties
    sentinel:
      transport:
        port: 10006
        dashboard: 127.0.0.1:8080

