spring:
  # 数据源配置项
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mall_admin?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  #    Spring Cloud 配置项
#  cloud:
#    nacos:
#      # Spring Cloud Nacos Discovery 配置项
#      discovery:
#        server-addr: 127.0.0.1:8848 # Nacos 服务器地址
#        namespace: dev # Nacos 命名空间
# Mall 认证安全配置
#mall.security.admin.demo: true # 是否开启演示模式