server:
  port: 6001

spring:
  profiles:
    active: dev
  application:
    name: auth-server
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/sc-plat?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=false&allowMultiQueries=true&zeroDateTimeBehavior=CONVERT_TO_NULL
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    timeout: 3000ms
    host: localhost

feign:
  okhttp:
    enabled: true
management:
  endpoint:
    health:
      enabled: true