spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
          lower-case-service-id: true
      routes:
        - id: user-center #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://sc-user-center # lb 开启负载均衡
          predicates:
            - Path=/user/**   #断言,路径相匹配的进行路由
        - id: user-order #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://sc-user-order # lb 开启负载均衡
          predicates:
            - Path=/order/**   #断言,路径相匹配的进行路由
sc:
  gateway:
    dynamicRoute:
      enabled: true
      dataType: nacos
      dataId: 'scg-routes'
      group: 'SCG_GATEWAY'

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: '*'