spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
          lower-case-service-id: true
      routes:
        - id: sc-auth   #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://sc-auth # lb 开启负载均衡
          predicates:
            - Path=/sc-auth/**   #断言,路径相匹配的进行路由
          filters:
            - StripPrefix=1
        - id: sc-admin   #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://sc-admin # lb 开启负载均衡
          predicates:
            - Path=/sc-admin/**   #断言,路径相匹配的进行路由
          filters:
            - StripPrefix=1
        - id: user-center #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://sc-user-center # lb 开启负载均衡
          predicates:
            - Path=/user/**   #断言,路径相匹配的进行路由
        - id: user-order #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://sc-user-order # lb 开启负载均衡
          predicates:
            - Path=/order/**   #断言,路径相匹配的进行路由
  redis:
    database: 0
    port: 6379
    host: localhost
    lettuce:
      pool:
        min-idle: 11
        max-active: 200
        max-wait: 60000
        shutdown-timeout: 100
sc:
  gateway:
    dynamicRoute:
      enabled: true
      dataType: nacos
      dataId: 'scg-routes'
      group: 'SCG_GATEWAY'

management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always