server:
  port: 8201
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #使用小写service-id
      routes: #配置路由路径
        - id: sc-admin
          uri: lb://sc-admin
          predicates:
            - Path=/sc-admin/**
          filters:
            - StripPrefix=1
  redis:
    database: 0
    port: 6379
    host: localhost
    password:
gateway:
  ignore:
    urls: #配置白名单路径
      - "/actuator/**"
      - "/sc-admin/sysUser/login"
      - "/sc-admin/sysUser/loginPhone"
      - "/sc-admin/sysUser/getAuthCode"

management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
